spring:
  datasource:
    url: jdbc:postgresql://\:\/\
    username: \
    password: \
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
        
server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
